### ISSUE TITLE
Doesn't work with recent versions of Flask

### ISSUE THREAD

**Issue by tfmorris** [okfn/bibserver#256]
From the mailing list:

>When following the instructions given at https://bibserver.readthedocs.org/en/latest/install.html "Install example", apparently all the steps are done properly but in the last command, when launching the  webserver I get:

>python bibserver/web.py 
>Traceback (most recent call last):
>  File "bibserver/web.py", line 21, in <module>
>    from bibserver.view.account import blueprint as account
>  File "/home/jabuntu14/bibserver/bibserver/view/account.py", line 6, in <module>
>    from flask.ext.wtf import Form, TextField, TextAreaField, PasswordField, validators, ValidationError
>  File "/home/jabuntu14/local/lib/python2.7/site-packages/flask/exthook.py", line 86, in load_module
>    raise ImportError('No module named %s' % fullname)
>ImportError: No module named flask.ext.wtf.TextField

The import needs to be switched to:

    from wtforms import TextField

instead of importing from flask.

**Comment by flowsta** [comment]
It was something wrong with new wtforms calling, pull request waiting for update

**Comment by tfmorris** [comment]
Fixed by PR #259.  Thanks @flowsta !
